name: C CI/CD

on:
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install and Configure Perf
      run: |
        sudo apt install linux-tools-common linux-tools-generic linux-tools-`uname -r`
        sudo apt install valgrind
        echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
    - name: Run Compare Build
      run: |
        make cmp
        ./main 512 512 512
        ./main 512 512 510
        ./main 1024 1024 1020
        ./main 1024 1024 1024
    - name: Check for Memory Leaks and Overflows
      run: |
        make asan
        ./main 2048 2048 2040
        ./main 4000 4000 420
    - name: Run Relase Build
      run: |
        make
        valgrind --tool=cachegrind --I1=32768,8,64 --D1=32768,8,64 --L2=262144,4,64 --LL=6291456,12,64 ./main 2048 1024 1912
        cg_annotate cachegrind*
        rm -rf cachegrind*
        valgrind --tool=cachegrind --I1=32768,8,64 --D1=32768,8,64 --L2=262144,4,64 --LL=6291456,12,64 ./main 512 1672 1002
        cg_annotate cachegrind*
        rm -rf cachegrind*
        valgrind --tool=cachegrind --I1=32768,8,64 --D1=32768,8,64 --L2=262144,4,64 --LL=6291456,12,64 ./main 2651 3412 4009
    - name: Show CPU Details
      run: |
        lscpu
