name: C CI/CD

on:
  push:
    branches: [ "experimental" ]
  pull_request:
    branches: [ "experimental" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Perf
      run: |
        sudo apt install linux-tools-common linux-tools-generic linux-tools-`uname -r`
    - name: Run Compare Build
      run: |
        make cmp
        ./main 512 512 512
        ./main 1024 1024 1024
    - name: Check for Memory Leaks and Overflows
      run: |
        make asan
        ./main 512 512 512
        ./main 1024 1024 1024
    - name: Run Relase Build
      run: |
        make
        perf -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./main 512 512 512
        perf -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./main 1024 1024 1024
        perf -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./main 2048 2048 2048
    - name: Show CPU Details
      run: |
        lscpu
